# Generated by Django 6.0.7 on 2026-07-26 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('hour_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='Club.club')),
            ],
        ),
    ]
