# Generated by Django 6.0.7 on 2026-07-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservationCode',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
