# Generated by Django 6.0.7 on 2026-08-01 11:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_booking_reservationcode'),
        ('FieldOwner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reserved_hours', models.PositiveIntegerField(default=0)),
                ('company_rate_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_company_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='money_calc', to='FieldOwner.fieldowner')),
            ],
        ),
    ]
