# Generated by Django 6.0.7 on 2026-08-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
