# Generated by Django 6.0.7 on 2026-07-26 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FieldOwner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('zone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('num_of_fields', models.PositiveIntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='FieldOwner.fieldowner')),
            ],
        ),
    ]
